#!/bin/sh
#
# dhcpcd        Starts dhcpcd.
#

# Make sure the dhcpcd binary exists
[ -f /sbin/dhcpcd ] || exit 0

umask 077

start() {

	printf "Starting dhcpcd: "
	/sbin/dhcpcd
	echo "OK"
}
stop() {
	printf "Stopping dhcpcd: "
	killall dhcpcd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

