#! /usr/bin/env python
# Copyright 2018 IBM Corp.
#
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


class software(object):
    """ Software installation class.
    """

    def __init__(self, eval_ver=False, non_int=False):
        pass

    def README(self):
        """ README method. Used to provide initial information to the user
        """
        print()
        print('A Power-Up software module class must implement the following '
              'methods:\n'
              '- README\n'
              '- prep\n'
              '- init_clients\n'
              '- install\n'
              '- status\n\n'
              'The software class init method must accept the following optional '
              'named arguments:\n'
              '- eval_ver: Used to indicate that an "evaluation" version of the\n'
              ' software is to be installed.\n'
              '- non_int: Used to indicate that the installation should run non\n'
              ' interactively. ie without user prompts\n\n'
              'Software modules must be valid python modules and must be placed\n'
              'in the power-up/software directory.\n')

    def prep(self):
        print('prep')

    def init_clients(self):
        print('init clients')

    def install(self):
        print('install')

    def status(self):
        print('status')


